---
title: "standardizaion_modeling"
author: "Matan & Hillel & Yael"
date: "2025-07-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE}
## libraries + internal utils
library(tidyverse)    # dplyr, ggplot2, purrr
library(glmnet)       # L1 logistic
library(ranger)       # random forest
library(doParallel)   # parallel bootstrap
library(foreach)
library(knitr)        # nice tables

source("utils/data_pipelines_utils.R")          # impute_df()
source("utils/plot_utils.R")                  # optional plotting
source("utils/causal_utils_standardization.R")
```

```{r}
base_df <- read_csv("data/full_cohort_data.csv", show_col_types = FALSE)

# Treatment & outcome
treatment <- "aline_flg"
outcome   <- "day_28_flg"

# Covariate blocks (identical to IPTW notebook)
individual_properties <- c(
  "age", "gender_num", "weight_first", "bmi"
)

severity_scores <- c(
  "sapsi_first", "sofa_first"
)

vital_signs <- c(
  "map_1st", "hr_1st", "temp_1st", "spo2_1st"
)

lab_results <- c(
  "wbc_first", "hgb_first", "platelet_first", "sodium_first",
  "potassium_first", "tco2_first", "chloride_first", "bun_first",
  "creatinine_first", "po2_first", "pco2_first"
)

first_day <- c("iv_day_1")

comorbidities <- c(
  "chf_flg", "afib_flg", "renal_flg", "liver_flg", "copd_flg",
  "cad_flg", "stroke_flg", "mal_flg", "resp_flg"
)

admission_properties <- c("service_unit", "day_icu_intime", "hour_icu_intime")

confounders <- c(
  individual_properties, severity_scores, vital_signs, lab_results,
  first_day, comorbidities, admission_properties
)

```

```{r}
# 2.1 drop BMI (too sparse)
clean_df <- base_df %>% select(-bmi)
clean_confounders <- confounders[!confounders %in% "bmi"]

# 2.2 create SOFA categorical to resolve positivity
final_base_df <- clean_df %>%
  mutate(sofa_first_cat = case_when(
    sofa_first < 2.5 ~ "0-2.5",
    sofa_first < 5   ~ "2.5-5",
    sofa_first < 7.5 ~ "5-7.5",
    sofa_first < 10  ~ "7.5-10",
    TRUE             ~ "10+"
  )) %>%
  select(-sofa_first)

final_confounders <- clean_confounders[!clean_confounders %in% "sofa_first"] %>%
  append("sofa_first_cat")

```

```{r}
df_no_na <- final_base_df %>%
  select(all_of(c(treatment, outcome, final_confounders))) %>%
  filter(complete.cases(.))

df_mean_imputed <- final_base_df %>%
  select(all_of(c(treatment, outcome, final_confounders))) %>%
  impute_df(method = "mean")

df_median_imputed <- final_base_df %>%
  select(all_of(c(treatment, outcome, final_confounders))) %>%
  impute_df(method = "median")

```

```{r}
run_pipeline <- function(df, dataset_name, model_type) {

  cat("----", dataset_name, "|", model_type, "----\n")

  # 4.1 outcome model
  fit <- model_outcome(
    df, final_confounders, treatment, outcome, model_type
  )

  # 4.2 counterfactual predictions
  preds <- predict_counterfactual(
    fit, df, final_confounders, treatment, outcome
  )

  # 4.3 point estimate
  est <- standardization_ate(preds)

  # 4.4 bootstrap variance (200 draws)
  boot <- bootstrap_standardization_ate(
    df, final_confounders, treatment, outcome,
    model_type        = model_type,
    n_bootstrap       = 200,
    plot_title        = sprintf("Bootstrap ATE – %s | %s",
                                dataset_name, model_type)
  )

  tibble(
    dataset  = dataset_name,
    model    = model_type,
    mu1      = est$mu1,
    mu0      = est$mu0,
    ATE      = est$ATE,
    CI_lower = boot$ci[1],
    CI_upper = boot$ci[2],
    SD       = boot$sd
  )
}

```

```{r}
datasets <- list(
  no_na          = df_no_na,
  mean_imputed   = df_mean_imputed,
  median_imputed = df_median_imputed
)

model_types <- c("logreg", "logreg_l1", "rf")

results_tbl <- purrr::map_dfr(
  names(datasets),
  function(dname) {
    df <- datasets[[dname]]
    purrr::map_dfr(
      model_types,
      ~ run_pipeline(df, dname, .x)
    )
  }
)
```

```{r}
kable(results_tbl,
      digits = 3,
      caption = "Standardisation ATE (bootstrap 95% CI, 200 draws)")
```
